"""Added review table

Revision ID: 4835cc89dca8
Revises: a267aa091b88
Create Date: 2026-03-19 00:38:38.986520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4835cc89dca8'
down_revision: Union[str, Sequence[str], None] = 'a267aa091b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('category',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # schema='shop'
    # )
    # op.create_index(op.f('ix_shop_category_id'), 'category', ['id'], unique=False, schema='shop')
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('username', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=False),
    # sa.Column('password', sa.String(), nullable=False),
    # sa.Column('role', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('username'),
    # schema='shop'
    # )
    # op.create_index(op.f('ix_shop_users_id'), 'users', ['id'], unique=False, schema='shop')
    # op.create_table('orders',
    # sa.Column('id', sa.String(length=10), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('customer_name', sa.String(), nullable=False),
    # sa.Column('customer_email', sa.String(), nullable=False),
    # sa.Column('status', sa.String(), nullable=False),
    # sa.Column('total', sa.Float(precision=2), nullable=False),
    # sa.Column('item_count', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['shop.users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='shop'
    # )
    # op.create_table('product',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('category_id', sa.Integer(), nullable=False),
    # sa.Column('price', sa.Float(), nullable=False),
    # sa.Column('stock', sa.Integer(), nullable=False),
    # sa.Column('sold', sa.Integer(), nullable=False),
    # sa.Column('emoji', sa.String(), nullable=True),
    # sa.Column('rating', sa.Float(), nullable=True),
    # sa.Column('reviews', sa.Integer(), nullable=True),
    # sa.Column('description', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['category_id'], ['shop.category.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='shop'
    # )
    # op.create_index(op.f('ix_shop_product_id'), 'product', ['id'], unique=False, schema='shop')
    # op.create_table('order_items',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('order_id', sa.String(length=10), nullable=False),
    # sa.Column('product_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('price', sa.Float(), nullable=False),
    # sa.Column('quantity', sa.Integer(), nullable=False),
    # sa.Column('subtotal', sa.Float(), nullable=False),
    # sa.ForeignKeyConstraint(['order_id'], ['shop.orders.id'], ),
    # sa.ForeignKeyConstraint(['product_id'], ['shop.product.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='shop'
    # )
    # op.create_index(op.f('ix_shop_order_items_id'), 'order_items', ['id'], unique=False, schema='shop')
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop.product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shop.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shop'
    )
    op.create_index(op.f('ix_shop_reviews_id'), 'reviews', ['id'], unique=False, schema='shop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_reviews_id'), table_name='reviews', schema='shop')
    op.drop_table('reviews', schema='shop')
    op.drop_index(op.f('ix_shop_order_items_id'), table_name='order_items', schema='shop')
    op.drop_table('order_items', schema='shop')
    op.drop_index(op.f('ix_shop_product_id'), table_name='product', schema='shop')
    op.drop_table('product', schema='shop')
    op.drop_table('orders', schema='shop')
    op.drop_index(op.f('ix_shop_users_id'), table_name='users', schema='shop')
    op.drop_table('users', schema='shop')
    op.drop_index(op.f('ix_shop_category_id'), table_name='category', schema='shop')
    op.drop_table('category', schema='shop')
    # ### end Alembic commands ###
