"""Add users table

Revision ID: 86d13d3d3f72
Revises: 
Create Date: 2026-03-16 17:23:55.987307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86d13d3d3f72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='shop'
    )
    op.create_index(op.f('ix_shop_users_id'), 'users', ['id'], unique=False, schema='shop')
    #op.drop_index(op.f('ix_users1_id'), table_name='users1')
    #op.drop_table('users1')
    #op.drop_index(op.f('ix_tasks1_id'), table_name='tasks1')
    #op.drop_table('tasks1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks1',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assignee_uname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignee_uname'], ['users1.username'], name=op.f('tasks1_assignee_uname_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks1_pkey'))
    )
    op.create_index(op.f('ix_tasks1_id'), 'tasks1', ['id'], unique=False)
    op.create_table('users1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pwd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Assigned_task_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users1_pkey')),
    sa.UniqueConstraint('username', name=op.f('users1_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users1_id'), 'users1', ['id'], unique=False)
    op.drop_index(op.f('ix_shop_users_id'), table_name='users', schema='shop')
    op.drop_table('users', schema='shop')
    # ### end Alembic commands ###
