"""Make nullable=True in product.reviews

Revision ID: fee524aa3a24
Revises: 665f53ddac1a
Create Date: 2026-03-17 16:40:04.969618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee524aa3a24'
down_revision: Union[str, Sequence[str], None] = '665f53ddac1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('category',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # schema='shop'
    # )
    # op.create_index(op.f('ix_shop_category_id'), 'category', ['id'], unique=False, schema='shop')
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('username', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=False),
    # sa.Column('password', sa.String(), nullable=False),
    # sa.Column('role', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('username'),
    # schema='shop'
    # )
    # op.create_index(op.f('ix_shop_users_id'), 'users', ['id'], unique=False, schema='shop')
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shop.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shop'
    )
    op.create_index(op.f('ix_shop_product_id'), 'product', ['id'], unique=False, schema='shop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_product_id'), table_name='product', schema='shop')
    op.drop_table('product', schema='shop')
    op.drop_index(op.f('ix_shop_users_id'), table_name='users', schema='shop')
    op.drop_table('users', schema='shop')
    op.drop_index(op.f('ix_shop_category_id'), table_name='category', schema='shop')
    op.drop_table('category', schema='shop')
    # ### end Alembic commands ###
